get_one_index_1: |-
  client.getIndex('movies').show()
list_all_indexes_1: |-
  client.listIndexes()
create_an_index_1: |-
  client.createIndex({ uid: 'movies' })
update_an_index_1: |-
  client.updateIndex({ uid: 'movies' })
delete_an_index_1: |-
  client.getIndex('movies').deleteIndex()
get_one_document_1: |-
  client.getDocument(1)
get_documents_1: |-
  client.getindex('movies').getDocuments({ limit: 2 })
add_or_replace_documents_1: |-
  client.getindex('movies').addDocuments([{
      id: 287947,
      title: 'Shazam',
      poster: 'https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
      overview: 'A boy is given the ability to become an adult superhero in times of need with a single magic word.',
      release_date: '2019-03-23'
  }])
add_or_update_documents_1: |-
  client.getindex('movies').updateDocuments([{
      movieskud: 287947,
      title: 'Shazam ⚡️'
  }])
delete_all_documents_1: |-
  client.getindex('movies').deleteAllDocuments()
delete_one_document_1: |-
  client.getindex('movies').deleteDocument(25684)
delete_documents_1: |-
  client.getindex('movies').deleteDocuments([23488, 153738, 437035, 363869])
search_1: |-
  client.getIndex('movies').search('American ninja')
get_update_1: |-
  client.getindex('movies').getUpdateStatus(1)
get_all_updates_1: |-
  client.getindex('movies').getAllUpdateStatus()
get_keys: |-
  client.getKeys()
get_settings_1: |-
  client.getindex('movies').getSettings()
update_settings_1: |-
  client.getindex('movies').updateSettings({
      rankingRules: [
          'typo',
          'words',
          'proximity',
          'attribute',
          'wordsPosition',
          'exactness',
          'desc(release_date)',
          'desc(rank)'
      ],
      distinctAttribute: 'movie_id',
      searchableAttributes: [
          'uid',
          'movie_id',
          'title',
          'description',
          'poster',
          'release_date',
          'rank'
      ],
      displayedAttributes: [
          'title',
          'description',
          'poster',
          'release_date',
          'rank'
      ],
      stopWords: [
          'the',
          'a',
          'an'
      ],
      synonyms: {
          'wolverine': ['xmen', 'logan'],
          'logan': ['wolverine']
      },
      acceptNewFields: false
  })
reset_settings_1: |-
  client.getindex('movies').resetSettings()
get_synonyms_1: |-
  client.getindex('movies').getSynonyms()
update_synonyms_1: |-
  client.getindex('movies').updateSynonym({
    wolverine: ['xmen', 'logan'],
    logan: ['wolverine', 'xmen'],
    wow: ['world of warcraft']
  })
reset_synonyms_1: |-
  client.getindex('movies').resetSynonym()
get_stop_words_1: |-
  client.getindex('movies').getStopWords()
update_stop_words_1: |-
  client.getindex('movies').updateStopWords(['of', 'the', 'to'])
reset_stop_words_1: |-
  client.getindex('movies').resetStopWords()
get_ranking_rules_1: |-
  client.getindex('movies').getRankingRules()
update_ranking_rules_1: |-
  client.getindex('movies').updateRankingRules([
      'typo',
      'words',
      'proximity',
      'attribute',
      'wordsPosition',
      'exactness',
      'asc(release_date)',
      'desc(rank)'
  ])
reset_ranking_rules_1: |-
  client.getindex('movies').resetRankingRules()
get_distinct_attribute_1: |-
  client.getindex('movies').getDistinctAttribute()
update_distinct_attribute_1: |-
  client.getindex('movies').updateDistinctAttribute('movie_id')
reset_distinct_attribute_1: |-
  client.getindex('movies').resetDistinctAttribute()
get_searchable_attributes_1: |-
  client.getindex('movies').getSearchableAttributes()
update_searchable_attributes_1: |-
  client.getindex('movies').updateSearchableAttributes([
      'title',
      'description',
      'uid'
  ])
reset_searchable_attributes_1: |-
  client.getindex('movies').resetSearchableAttributes()
get_displayed_attributes_1: |-
  client.getindex('movies').getDisplayedAttributes()
update_displayed_attributes_1: |-
  client.getindex('movies').updateDisplayedAttributes([
      'title',
      'description',
      'release_date',
      'rank',
      'poster'
  ])
reset_displayed_attributes_1: |-
  client.getindex('movies').resetDisplayedAttributes()
get_accept_new_fields_1: |-
  client.getindex('movies').getAcceptNewFields()
update_accept_new_fields_1: |-
  client.getindex('movies').updateAcceptNewFields(false)
get_index_stats_1: |-
  client.getindex('movies').getStats()
get_indexes_stats_1: |-
  client.stats()
get_health_1: |-
  client.isHealthy()
update_health_1: |-
get_version_1: |-
  client.version()
get_pretty_sys_info_1: |-
  client.systemInformationPretty()
get_sys_info_1: |-
  client.systemInformation()
